apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: privilee-app  # Replace with your app namespace variable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: privilee-app
  template:
    metadata:
      labels:
        app: privilee-app
    spec:
      containers:
      - name: privilee-app
        image: 493892691932.dkr.ecr.me-south-1.amazonaws.com/privilee/hello-world:latest  # Replace with your actual image
        ports:
        - containerPort: 1323
