name: CI/CD Workflow

on: [push]

jobs:

  setup-go-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Initialize Go Module
        run: go mod init ${{ secrets.MODULE_PATH }}
      - name: Install dependencies
        run: go mod tidy
      - name: Upload go.mod as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: go-files
          path: |
            go.mod
            go.sum 

  build:
    needs: setup-go-module
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get go files
      uses: actions/download-artifact@v2
      with:
        name: go-files
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Build
      run: go build -v ./...

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get go files
      uses: actions/download-artifact@v2
      with:
        name: go-files
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16' 
    - name: Test
      run: go test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
